*  Name-Yashasavi Jain

*  PRN-25070123127

*  Batch-B3

*  Aim-Study of Numpy Laibrary

In [30]:
# Declaration of Numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
display(a.dtype)
print(b * 2)
print(a + 5)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


dtype('int64')

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [13]:
# Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [19]:
print(a.shape)

(7,)


In [18]:
print(b.shape)

(2, 3)


In [17]:
print(a.dtype)

int64


In [20]:
# In-Built functions using Numpy
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
print(np.eye((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [26]:
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [31]:
print(np.mean(a))

93.0


In [33]:
print(np.median(a))

30.0


In [35]:
print(np.max(a))

500


In [36]:
print(np.sum(a))

651


In [37]:
print(np.min(a))

1
